In [1]:
import pandas as pd
import numpy as np
np.set_printoptions(precision=3,suppress=True)

import tensorflow as tf
from tensorflow.keras import layers

In [3]:
abalone_train = pd.read_csv("https://storage.googleapis.com/download.tensorflow.org/data/abalone_train.csv",
                            names=["Length","Diameter","Height","Whole weight","Shucked weight",
                                   "Viscera weight","Shell weight","Age"])
abalone_train.head()

Length 
 Diameter 
 Height 
 Whole weight 
 Shucked weight 
 Viscera weight 
 Shell weight 
 Age 
 
 
 
 
 0 
 0.435 
 0.335 
 0.110 
 0.334 
 0.1355 
 0.0775 
 0.0965 
 7 
 
 
 1 
 0.585 
 0.450 
 0.125 
 0.874 
 0.3545 
 0.2075 
 0.2250 
 6 
 
 
 2 
 0.655 
 0.510 
 0.160 
 1.092 
 0.3960 
 0.2825 
 0.3700 
 14 
 
 
 3 
 0.545 
 0.425 
 0.125 
 0.768 
 0.2940 
 0.1495 
 0.2600 
 16 
 
 
 4 
 0.545 
 0.420 
 0.130 
 0.879 
 0.3740 
 0.1695 
 0.2300 
 13

In [4]:
abalone_features = abalone_train.copy()
abalone_labels = abalone_features.pop('Age')

In [6]:
abalone_features = np.array(abalone_features)
print(abalone_features)

[[0.435 0.335 0.11  ... 0.136 0.077 0.097]
 [0.585 0.45  0.125 ... 0.354 0.207 0.225]
 [0.655 0.51  0.16  ... 0.396 0.282 0.37 ]
 ...
 [0.53  0.42  0.13  ... 0.374 0.167 0.249]
 [0.395 0.315 0.105 ... 0.118 0.091 0.119]
 [0.45  0.355 0.12  ... 0.115 0.067 0.16 ]]


In [7]:
#zbiór TITANIC
titanic = pd.read_csv("https://storage.googleapis.com/tf-datasets/titanic/train.csv")
titanic.head()

survived 
 sex 
 age 
 n_siblings_spouses 
 parch 
 fare 
 class 
 deck 
 embark_town 
 alone 
 
 
 
 
 0 
 0 
 male 
 22.0 
 1 
 0 
 7.2500 
 Third 
 unknown 
 Southampton 
 n 
 
 
 1 
 1 
 female 
 38.0 
 1 
 0 
 71.2833 
 First 
 C 
 Cherbourg 
 n 
 
 
 2 
 1 
 female 
 26.0 
 0 
 0 
 7.9250 
 Third 
 unknown 
 Southampton 
 y 
 
 
 3 
 1 
 female 
 35.0 
 1 
 0 
 53.1000 
 First 
 C 
 Southampton 
 n 
 
 
 4 
 0 
 male 
 28.0 
 0 
 0 
 8.4583 
 Third 
 unknown 
 Queenstown 
 y

In [8]:
titanic_features = titanic.copy()
titanic_labels = titanic_features.pop('survived')

In [10]:
#wstępne przygotowanie zbioru
input = tf.keras.Input(shape=(), dtype=tf.float32)
result = 2*input+1
result

<KerasTensor: shape=(None,) dtype=float32 (created by layer 'tf.__operators__.add')>

In [11]:
calc = tf.keras.Model(inputs = input, outputs=result)

In [12]:
print(calc(1).numpy())
print(calc(2).numpy())

3.0
5.0


In [16]:
inputs = {}
for name,column in titanic_features.items():
    dtype = column.dtype
    if dtype == object:
        dtype = tf.string
    else:
        dtype = tf.float32
    inputs[name] = tf.keras.Input(shape=(1,),name=name,dtype=dtype)

inputs

{'sex': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'sex')>,
 'age': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'age')>,
 'n_siblings_spouses': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'n_siblings_spouses')>,
 'parch': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'parch')>,
 'fare': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'fare')>,
 'class': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'class')>,
 'deck': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'deck')>,
 'embark_town': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'embark_town')>,
 'alone': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'alone')>}