In [1]:
import pandas as pd
import numpy as np
np.set_printoptions(precision=3,suppress=True)

import tensorflow as tf
from tensorflow.keras import layers

In [3]:
abalone_train = pd.read_csv("https://storage.googleapis.com/download.tensorflow.org/data/abalone_train.csv",
                            names=["Length","Diameter","Height","Whole weight","Shucked weight",
                                   "Viscera weight","Shell weight","Age"])
abalone_train.head()

Length 
 Diameter 
 Height 
 Whole weight 
 Shucked weight 
 Viscera weight 
 Shell weight 
 Age 
 
 
 
 
 0 
 0.435 
 0.335 
 0.110 
 0.334 
 0.1355 
 0.0775 
 0.0965 
 7 
 
 
 1 
 0.585 
 0.450 
 0.125 
 0.874 
 0.3545 
 0.2075 
 0.2250 
 6 
 
 
 2 
 0.655 
 0.510 
 0.160 
 1.092 
 0.3960 
 0.2825 
 0.3700 
 14 
 
 
 3 
 0.545 
 0.425 
 0.125 
 0.768 
 0.2940 
 0.1495 
 0.2600 
 16 
 
 
 4 
 0.545 
 0.420 
 0.130 
 0.879 
 0.3740 
 0.1695 
 0.2300 
 13

In [4]:
abalone_features = abalone_train.copy()
abalone_labels = abalone_features.pop('Age')

In [6]:
abalone_features = np.array(abalone_features)
print(abalone_features)

[[0.435 0.335 0.11  ... 0.136 0.077 0.097]
 [0.585 0.45  0.125 ... 0.354 0.207 0.225]
 [0.655 0.51  0.16  ... 0.396 0.282 0.37 ]
 ...
 [0.53  0.42  0.13  ... 0.374 0.167 0.249]
 [0.395 0.315 0.105 ... 0.118 0.091 0.119]
 [0.45  0.355 0.12  ... 0.115 0.067 0.16 ]]


In [ ]:
#zbiór TITANIC