In [2]:
import numpy as np

In [3]:
#funkcje uniwersalne

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([0. , 1. , 1.41421356, 1.73205081, 2. ,
 2.23606798, 2.44948974, 2.64575131, 2.82842712, 3. ])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
 5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
 2.98095799e+03, 8.10308393e+03])

In [8]:
x=np.random.randn(8)
y=np.random.randn(8)
(x,y)

(array([ 1.92700898,  0.57215058, -1.57906923, -0.20922281,  2.162429  ,
         0.37606546, -0.03100873, -0.80317459]),
 array([-2.47696011, -0.67121292,  0.13727531,  0.84457226, -1.85474669,
        -0.6636322 ,  0.16955579, -0.96092864]))

In [9]:
np.maximum(x,y)

array([ 1.92700898, 0.57215058, 0.13727531, 0.84457226, 2.162429 ,
 0.37606546, 0.16955579, -0.80317459])

In [10]:
arr = np.random.randn(7)*5
arr

array([ 2.48736565, -1.01063848, 4.87832545, 0.79128979, -8.73815501,
 -2.65712587, -0.37312698])

In [11]:
remainder,whole_part = np.modf(arr)

In [12]:
remainder

array([ 0.48736565, -0.01063848, 0.87832545, 0.79128979, -0.73815501,
 -0.65712587, -0.37312698])

In [13]:
whole_part

array([ 2., -1., 4., 0., -8., -2., -0.])

In [14]:
arr

array([ 2.48736565, -1.01063848, 4.87832545, 0.79128979, -8.73815501,
 -2.65712587, -0.37312698])

In [15]:
np.sqrt(arr)

<ipython-input-15-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([1.57713844, nan, 2.20869315, 0.88954471, nan,
 nan, nan])

In [16]:
np.sqrt(arr,arr)

<ipython-input-16-e3ca18b15869>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr,arr)


array([1.57713844, nan, 2.20869315, 0.88954471, nan,
 nan, nan])