In [1]:
import numpy as np

In [2]:
#metody matematyczne i statystyczne
arr = np.random.randn(5,4)
arr

array([[-0.92649848, 0.16143437, 1.34384974, -0.45371541],
 [-0.007172 , 0.54745531, 0.19777398, 0.79535482],
 [-0.92568064, -1.36398769, -0.18645617, 0.75801123],
 [ 0.65199332, 0.28657994, 1.42220422, -0.54984062],
 [-0.77801494, -0.55107159, 0.2207759 , -0.54893929]])

In [3]:
arr.mean()

0.0047027995410506675

In [6]:
arr.mean(axis=1)

array([ 0.03126755, 0.38335303, -0.42952832, 0.45273421, -0.41431248])

In [7]:
arr = np.array([0,2,4,5,6,7,9,11,22])
arr.cumsum()

array([ 0, 2, 6, 11, 17, 24, 33, 44, 66])

In [8]:
arr = np.array([[0,1,2],[6,7,8],[10,15,19]])
arr

array([[ 0, 1, 2],
 [ 6, 7, 8],
 [10, 15, 19]])

In [9]:
arr.cumsum(axis=0)

array([[ 0, 1, 2],
 [ 6, 8, 10],
 [16, 23, 29]])

In [11]:
arr.cumprod(axis=1)

array([[ 0, 0, 0],
 [ 6, 42, 336],
 [ 10, 150, 2850]])

In [12]:
#metody tablic logicznych
arr = np.random.randn(100)
(arr>0).sum()

43

In [13]:
bools = np.array([False,False,True,False])
bools.any()

True

In [14]:
bools.all()

False

In [ ]:
#wartości unikalne  i operacje logiczne na zbiorach