In [11]:
import numpy as np

In [12]:
arr = np.array([[1.,2.,3.],[6.,8.,9.]])
arr

array([[1., 2., 3.],
 [6., 8., 9.]])

In [13]:
arr*arr

array([[ 1., 4., 9.],
 [36., 64., 81.]])

In [14]:
arr-arr

array([[0., 0., 0.],
 [0., 0., 0.]])

In [15]:
1/arr

array([[1. , 0.5 , 0.33333333],
 [0.16666667, 0.125 , 0.11111111]])

In [16]:
arr**0.5

array([[1. , 1.41421356, 1.73205081],
 [2.44948974, 2.82842712, 3. ]])

In [17]:
arr2 = np.array([[0.,4.,1.],[7.,5.,14.]])
arr2

array([[ 0., 4., 1.],
 [ 7., 5., 14.]])

In [18]:
arr2>arr

array([[False, True, False],
 [ True, False, True]])

In [19]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [20]:
arr2d[0][2]

3

In [21]:
arr2d[0,2]

3

In [23]:
zl = [[1,2,3],[4,5,6],[7,8,9]]

In [24]:
zl[0][2]

3

In [26]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr3d[0]

array([[1, 2, 3],
 [4, 5, 6]])

In [28]:
arr3d[1]

array([[ 7, 8, 9],
 [10, 11, 12]])

In [29]:
old_values = arr3d[0].copy()
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
arr3d[1,0,1]

8

In [35]:
arr3d.shape

(2, 2, 3)

In [36]:
names = np.array(['Olek','Anna','Piotr','Leon','Anna','Jan','Jan'])
data = np.random.randn(7,4)
names

array(['Olek', 'Anna', 'Piotr', 'Leon', 'Anna', 'Jan', 'Jan'], dtype='%lt;U5')

In [37]:
data

array([[ 0.55101181, 0.80284508, 0.03207375, -0.22170979],
 [-0.98381018, -0.4974583 , 0.18958798, 2.69763193],
 [-1.69977827, -1.69309975, 0.84966665, 1.72442334],
 [ 0.09673967, 0.82961862, -0.50585894, -0.22291162],
 [-0.18738336, 0.75910398, 0.41537938, 0.71069471],
 [ 1.74927986, -1.45734864, -1.68049239, 0.86784638],
 [-1.53912826, -0.72881836, 0.66615015, 0.30100792]])

In [38]:
names == 'Jan'

array([False, False, False, False, False, True, True])

In [39]:
data[names=="Jan"]

array([[ 1.74927986, -1.45734864, -1.68049239, 0.86784638],
 [-1.53912826, -0.72881836, 0.66615015, 0.30100792]])

In [40]:
data[names=="Jan",2:]

array([[-1.68049239, 0.86784638],
 [ 0.66615015, 0.30100792]])

In [41]:
data[names=="Jan",3]

array([0.86784638, 0.30100792])

In [42]:
names != "Jan"

array([ True, True, True, True, True, False, False])

In [43]:
data[~(names=='Jan')]

array([[ 0.55101181, 0.80284508, 0.03207375, -0.22170979],
 [-0.98381018, -0.4974583 , 0.18958798, 2.69763193],
 [-1.69977827, -1.69309975, 0.84966665, 1.72442334],
 [ 0.09673967, 0.82961862, -0.50585894, -0.22291162],
 [-0.18738336, 0.75910398, 0.41537938, 0.71069471]])

In [44]:
cond = names == "Jan"
data[~cond]

array([[ 0.55101181, 0.80284508, 0.03207375, -0.22170979],
 [-0.98381018, -0.4974583 , 0.18958798, 2.69763193],
 [-1.69977827, -1.69309975, 0.84966665, 1.72442334],
 [ 0.09673967, 0.82961862, -0.50585894, -0.22291162],
 [-0.18738336, 0.75910398, 0.41537938, 0.71069471]])

In [45]:
mask = (names=="Jan") | (names=='Anna')
mask

array([False, True, False, False, True, True, True])

In [46]:
data[mask]

array([[-0.98381018, -0.4974583 , 0.18958798, 2.69763193],
 [-0.18738336, 0.75910398, 0.41537938, 0.71069471],
 [ 1.74927986, -1.45734864, -1.68049239, 0.86784638],
 [-1.53912826, -0.72881836, 0.66615015, 0.30100792]])

In [47]:
data[data<0] = 0
data

array([[0.55101181, 0.80284508, 0.03207375, 0. ],
 [0. , 0. , 0.18958798, 2.69763193],
 [0. , 0. , 0.84966665, 1.72442334],
 [0.09673967, 0.82961862, 0. , 0. ],
 [0. , 0.75910398, 0.41537938, 0.71069471],
 [1.74927986, 0. , 0. , 0.86784638],
 [0. , 0. , 0.66615015, 0.30100792]])