In [36]:
import numpy as np

In [37]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [38]:
ar = np.ones(9)
print(ar)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [39]:
np.empty(8)

array([4.63822006e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000])

In [40]:
u=np.arange(1,77,3)
print(u)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76]


In [41]:
h = [4,8,99,1,3,55,3]
print(type(h))
print(type(u))

<class 'list'>
<class 'numpy.ndarray'>


In [42]:
k = np.linspace(0,10,num=5)
print(k)

[ 0.   2.5  5.   7.5 10. ]


In [43]:
mlista = np.array([45,7,89,7,5,4,22,34])
print(mlista)
print(type(mlista))

[45  7 89  7  5  4 22 34]
<class 'numpy.ndarray'>


In [44]:
dlista = np.array(h)
print(dlista)
print(type(dlista))

[ 4  8 99  1  3 55  3]
<class 'numpy.ndarray'>


In [45]:
kl = (9,4,5,2,44,5,7)
npk = np.array(kl)
print(npk)

zb = {5,3,2,44,6,7,7,8,7}
zbk = np.array(zb)
print(zbk)
print(type(zbk))

[ 9  4  5  2 44  5  7]
{2, 3, 5, 6, 7, 8, 44}
<class 'numpy.ndarray'>


In [46]:
nb = [45,7,8,3,1,35,77,-99,0,12,112,-654,1235]
nnb = np.array(nb)
print(nnb)

[  45    7    8    3    1   35   77  -99    0   12  112 -654 1235]


In [47]:
nb.sort()
nb

[-654, -99, 0, 1, 3, 7, 8, 12, 35, 45, 77, 112, 1235]

In [48]:
nnb.sort()
nnb

array([-654, -99, 0, 1, 3, 7, 8, 12, 35, 45, 77,
 112, 1235])

In [49]:
a=np.array([1,5,8,11])
b=np.array([2,5,9,13])
c=np.array([56,99])
big = np.concatenate((a,b,c))
print(big)

[ 1  5  8 11  2  5  9 13 56 99]


In [50]:
#twrzorzenie macierzy
x = np.array([[3,4],[19,6]])
print(x)

y = np.array([[7,11],[45,2]])
print(y)
zx = [[3,4],[19,6]]
print(zx)

[[ 3  4]
 [19  6]]
[[ 7 11]
 [45  2]]
[[3, 4], [19, 6]]


In [51]:
p = np.concatenate((x,y),axis=0)
print(p)

[[ 3  4]
 [19  6]
 [ 7 11]
 [45  2]]


In [56]:
prosta = np.arange(12)
print(prosta)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [57]:
pp = prosta.reshape(3,4)
print(pp)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [60]:
fp = pp.reshape(12)
print(fp)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [68]:
ar = np.array([1,6,78,9,112,7,80,-5,12,34,55,67,89])
print(ar.shape)

(13,)


In [69]:
print(ar[:4])

[ 1  6 78  9]


In [70]:
print(ar[5:])

[ 7 80 -5 12 34 55 67 89]


In [72]:
print(ar[3:7])

[  9 112   7  80]


In [73]:
w = np.array([[1,2,3,4],[99,34,56,77],[21,13,14,35]])
print(w)

[[ 1  2  3  4]
 [99 34 56 77]
 [21 13 14 35]]


In [74]:
print(w[w<5])

[1 2 3 4]


In [76]:
pc = (w>=5)
print(w[pc])

[99 34 56 77 21 13 14 35]


In [77]:
pv = (w%2==0)
print(w[pv])

[ 2  4 34 56 14]


In [78]:
c = w[(w>2)&(w<21)]
print(c)

[ 3  4 13 14]


In [79]:
s = w[(w<8)|(w>50)]
print(s)

[ 1  2  3  4 99 56 77]


In [80]:
dane = np.array([1,3,8])
ones = np.ones(3,dtype=int)
tw = np.array([2,2,3])

In [81]:
print(dane+ones)

[2 4 9]


In [82]:
print(dane-ones)

[0 2 7]


In [83]:
print(dane*tw)

[ 2  6 24]


In [84]:
print(dane/tw)

[0.5        1.5        2.66666667]


In [85]:
tab = np.array([[1,6],[27,19]])
print(tab)

[[ 1  6]
 [27 19]]


In [87]:
print(tab.sum(axis=0))
print(tab.sum(axis=1))

[28 25]
[ 7 46]


In [88]:
print(tab*1.896)

[[ 1.896 11.376]
 [51.192 36.024]]


In [89]:
print(tab.max())
print(tab.min())
print(tab.mean())

27
1
13.25
