In [11]:
import numpy as np

In [12]:
arr = np.array([[1.,2.,3.],[6.,8.,9.]])
arr

array([[1., 2., 3.],
 [6., 8., 9.]])

In [13]:
arr*arr

array([[ 1., 4., 9.],
 [36., 64., 81.]])

In [14]:
arr-arr

array([[0., 0., 0.],
 [0., 0., 0.]])

In [15]:
1/arr

array([[1. , 0.5 , 0.33333333],
 [0.16666667, 0.125 , 0.11111111]])

In [16]:
arr**0.5

array([[1. , 1.41421356, 1.73205081],
 [2.44948974, 2.82842712, 3. ]])

In [17]:
arr2 = np.array([[0.,4.,1.],[7.,5.,14.]])
arr2

array([[ 0., 4., 1.],
 [ 7., 5., 14.]])

In [18]:
arr2>arr

array([[False, True, False],
 [ True, False, True]])

In [19]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [20]:
arr2d[0][2]

3

In [21]:
arr2d[0,2]

3

In [23]:
zl = [[1,2,3],[4,5,6],[7,8,9]]

In [24]:
zl[0][2]

3

In [26]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr3d[0]

array([[1, 2, 3],
 [4, 5, 6]])

In [28]:
arr3d[1]

array([[ 7, 8, 9],
 [10, 11, 12]])

In [29]:
old_values = arr3d[0].copy()
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
arr3d[1,0,1]

8

In [35]:
arr3d.shape

(2, 2, 3)

In [36]:
names = np.array(['Olek','Anna','Piotr','Leon','Anna','Jan','Jan'])
data = np.random.randn(7,4)
names

array(['Olek', 'Anna', 'Piotr', 'Leon', 'Anna', 'Jan', 'Jan'], dtype='%lt;U5')

In [37]:
data

array([[ 0.55101181, 0.80284508, 0.03207375, -0.22170979],
 [-0.98381018, -0.4974583 , 0.18958798, 2.69763193],
 [-1.69977827, -1.69309975, 0.84966665, 1.72442334],
 [ 0.09673967, 0.82961862, -0.50585894, -0.22291162],
 [-0.18738336, 0.75910398, 0.41537938, 0.71069471],
 [ 1.74927986, -1.45734864, -1.68049239, 0.86784638],
 [-1.53912826, -0.72881836, 0.66615015, 0.30100792]])

In [38]:
names == 'Jan'

array([False, False, False, False, False, True, True])

In [39]:
data[names=="Jan"]

array([[ 1.74927986, -1.45734864, -1.68049239, 0.86784638],
 [-1.53912826, -0.72881836, 0.66615015, 0.30100792]])

In [40]:
data[names=="Jan",2:]

array([[-1.68049239, 0.86784638],
 [ 0.66615015, 0.30100792]])

In [41]:
data[names=="Jan",3]

array([0.86784638, 0.30100792])

In [42]:
names != "Jan"

array([ True, True, True, True, True, False, False])

In [43]:
data[~(names=='Jan')]

array([[ 0.55101181, 0.80284508, 0.03207375, -0.22170979],
 [-0.98381018, -0.4974583 , 0.18958798, 2.69763193],
 [-1.69977827, -1.69309975, 0.84966665, 1.72442334],
 [ 0.09673967, 0.82961862, -0.50585894, -0.22291162],
 [-0.18738336, 0.75910398, 0.41537938, 0.71069471]])

In [44]:
cond = names == "Jan"
data[~cond]

array([[ 0.55101181, 0.80284508, 0.03207375, -0.22170979],
 [-0.98381018, -0.4974583 , 0.18958798, 2.69763193],
 [-1.69977827, -1.69309975, 0.84966665, 1.72442334],
 [ 0.09673967, 0.82961862, -0.50585894, -0.22291162],
 [-0.18738336, 0.75910398, 0.41537938, 0.71069471]])

In [45]:
mask = (names=="Jan") | (names=='Anna')
mask

array([False, True, False, False, True, True, True])

In [46]:
data[mask]

array([[-0.98381018, -0.4974583 , 0.18958798, 2.69763193],
 [-0.18738336, 0.75910398, 0.41537938, 0.71069471],
 [ 1.74927986, -1.45734864, -1.68049239, 0.86784638],
 [-1.53912826, -0.72881836, 0.66615015, 0.30100792]])

In [47]:
data[data<0] = 0
data

array([[0.55101181, 0.80284508, 0.03207375, 0. ],
 [0. , 0. , 0.18958798, 2.69763193],
 [0. , 0. , 0.84966665, 1.72442334],
 [0.09673967, 0.82961862, 0. , 0. ],
 [0. , 0.75910398, 0.41537938, 0.71069471],
 [1.74927986, 0. , 0. , 0.86784638],
 [0. , 0. , 0.66615015, 0.30100792]])

In [48]:
data[names!='Olek'] = 8
data

array([[0.55101181, 0.80284508, 0.03207375, 0. ],
 [8. , 8. , 8. , 8. ],
 [8. , 8. , 8. , 8. ],
 [8. , 8. , 8. , 8. ],
 [8. , 8. , 8. , 8. ],
 [8. , 8. , 8. , 8. ],
 [8. , 8. , 8. , 8. ]])

In [49]:
#indeksowanie specjalne
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
 [1., 1., 1., 1.],
 [2., 2., 2., 2.],
 [3., 3., 3., 3.],
 [4., 4., 4., 4.],
 [5., 5., 5., 5.],
 [6., 6., 6., 6.],
 [7., 7., 7., 7.]])

In [50]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
 [3., 3., 3., 3.],
 [0., 0., 0., 0.],
 [6., 6., 6., 6.]])

In [51]:
arr[[-3,-6,-8]]

array([[5., 5., 5., 5.],
 [2., 2., 2., 2.],
 [0., 0., 0., 0.]])

In [52]:
#transponowanie tablic i zmiana osi

arr = np.arange(15).reshape((3,5))
arr

array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])

In [53]:
arr.T

array([[ 0, 5, 10],
 [ 1, 6, 11],
 [ 2, 7, 12],
 [ 3, 8, 13],
 [ 4, 9, 14]])

In [54]:
arr = np.random.randn(6,3)
arr

array([[ 0.70443951, 0.35869101, 0.64831301],
 [-0.37579511, -1.35311771, -0.7051896 ],
 [-0.61433452, -0.37487214, -1.57438623],
 [-0.85880136, -0.56885579, 0.81976994],
 [-0.38372605, -1.14822291, -1.01494502],
 [ 0.18533577, 0.50114549, -0.14425079]])

In [55]:
arr.T

array([[ 0.70443951, -0.37579511, -0.61433452, -0.85880136, -0.38372605,
 0.18533577],
 [ 0.35869101, -1.35311771, -0.37487214, -0.56885579, -1.14822291,
 0.50114549],
 [ 0.64831301, -0.7051896 , -1.57438623, 0.81976994, -1.01494502,
 -0.14425079]])

In [56]:
np.dot(arr.T,arr)

array([[1.9339987 , 2.01348539, 1.34761038],
 [2.01348539, 3.99327548, 2.40370374],
 [1.34761038, 2.40370374, 5.11923856]])

In [62]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [63]:
arr2 = arr.transpose((1,0,2))
arr2

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [64]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [66]:
arr3 = arr.swapaxes(1,2)
arr3

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [68]:
print(arr.shape)
print(arr2.shape)
print(arr3.shape)

(2, 2, 4)
(2, 2, 4)
(2, 4, 2)
